apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: nextcloud-app
    app.kubernetes.io/name: nextcloud
  name: app
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app.kubernetes.io/component: nextcloud-app
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  labels:
    app.kubernetes.io/component: nextcloud-app
    app.kubernetes.io/name: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  labels:
    app.kubernetes.io/component: nextcloud-app
    app.kubernetes.io/name: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: nextcloud-app
    app.kubernetes.io/name: nextcloud
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nextcloud-app
        app.kubernetes.io/name: nextcloud
    spec:
      containers:
      - name: app
        image: app
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db
              key: MYSQL_USER
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: db
              key: MYSQL_HOST
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis
              key: REDIS_HOST
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html/data
        - name: nextcloud-config
          mountPath: /var/www/html/config
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data
      - name: nextcloud-config
        persistentVolumeClaim:
          claimName: nextcloud-config
