apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: nextcloud-redis
    app.kubernetes.io/name: nextcloud
  name: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app.kubernetes.io/component: nextcloud-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: nextcloud-redis
    app.kubernetes.io/name: nextcloud
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nextcloud-redis
        app.kubernetes.io/name: nextcloud
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
