apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: nextcloud-cron
    app.kubernetes.io/name: nextcloud
  name: cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nextcloud-cron
        app.kubernetes.io/name: nextcloud
    spec:
      containers:
      - name: cron
        image: app
        command: ["/bin/sh", "-c", "/cron.sh"]
        volumeMounts:
        - name: cron
          mountPath: /var/www/html
      volumes:
      - name: cron
        persistentVolumeClaim:
          claimName: app
