apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: nextcloud-webapp
    app.kubernetes.io/name: nextcloud
  name: app
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app.kubernetes.io/component: nextcloud-webapp
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-volume
  labels:
    app.kubernetes.io/component: nextcloud-webapp
    app.kubernetes.io/name: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-g9-enp4s0
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app
  labels:
    app.kubernetes.io/component: nextcloud-webapp
    app.kubernetes.io/name: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-g9-enp4s0
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: nextcloud-webapp
    app.kubernetes.io/name: nextcloud
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nextcloud-webapp
        app.kubernetes.io/name: nextcloud
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 33:33 /var/www/html/config"]
          volumeMounts:
            - name: cron
              mountPath: /var/www/html
      containers:
      - name: app
        image: app
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db
              key: MYSQL_USER
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: db
              key: MYSQL_HOST    
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis
              key: REDIS_HOST
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app
          mountPath: /var/www/html
        - name: config-volume
          mountPath: /var/www/html/config
      securityContext:
        fsGroup: 33
      volumes:
      - name: app
        persistentVolumeClaim:
          claimName: app
      - name: config-volume
        persistentVolumeClaim:
          claimName: config-volume