apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-apache-extra-config
  namespace: nextcloud
data:
  nextcloud-video.conf: |
    <IfModule mod_headers.c>
        Header set Accept-Ranges bytes
        Header always set X-Content-Type-Options "nosniff"
    </IfModule>

    <IfModule mod_mime.c>
        AddType video/mp4 .mp4
        AddType video/webm .webm
        AddType video/ogg .ogv
    </IfModule>