apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - ../../base
  - avp-secret.yaml
configMapGenerator:
- name: db
  literals:
    - MYSQL_HOST=nextcloud-db-production:3306
- name: redis
  literals:
    - REDIS_HOST=nextcloud-redis-production
#- name: config-nginx
#  files:
#  - custom-nginx.conf=configmap-nginx.conf
transformers:
  - transformer-label.yaml
  - transformer-suffixprefix.yaml
images:
  #- name: web
  #  newName: nginx
  #  newTag: "1.25.3-alpine"
  - name: app
    newName: nextcloud
    newTag: "29.0.4-apache"
  - name: cron
    newName: nextcloud
    newTag: "29.0.4-apache"
  - name: redis
    newName: redis
    newTag: "7.2.4-alpine"
  - name: db
    newName: mariadb
    newTag: "10.5"
replicas:
- name: app
  count: 1
patches:
### storage ###
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: app
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: app
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 15Gi
        storageClassName: longhorn
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: db
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: longhorn
### reesources ###
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: web
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web
      spec:
        template:
          spec:
            containers:
            - name: web
              resources:
                requests:
                  cpu: "350m"
                  memory: "500Mi"
                limits:
                  cpu: "850m"
                  memory: "1200Mi"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: app
      spec:
        template:
          spec:
            containers:
            - name: app
              resources:
                requests:
                  cpu: "350m"
                  memory: "500Mi"
                limits:
                  cpu: "1300m"
                  memory: "1500Mi"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cron
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cron
      spec:
        template:
          spec:
            containers:
            - name: cron
              resources:
                requests:
                  cpu: "150m"
                  memory: "100Mi"
                limits:
                  cpu: "550m"
                  memory: "300Mi"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: redis
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: redis
      spec:
        template:
          spec:
            containers:
            - name: redis
              resources:
                requests:
                  cpu: "150m"
                  memory: "500Mi"
                limits:
                  cpu: "550m"
                  memory: "850Mi"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: db
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: db
      spec:
        template:
          spec:
            containers:
            - name: db
              resources:
                requests:
                  cpu: "250m"
                  memory: "250Mi"
                limits:
                  cpu: "500m"
                  memory: "750Mi"
