apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  config.php: |
    <?php
    $CONFIG = array (
      'overwrite.cli.url' => 'https://nextcloud.aimhighergg.com',
      'overwritehost' => 'nextcloud.aimhighergg.com',
      'overwriteprotocol' => 'https',
      'trusted_proxies' =>
      array (
        0 => '10.0.0.0/8',
      ),
    );
