apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  config.php: |
    <?php
    $CONFIG = array (
      'overwrite.cli.url' => 'https://nextcloud.aimhighergg.com',
      'overwritehost' => 'nextcloud.aimhighergg.com',
      'overwriteprotocol' => 'https',
      'trusted_proxies' => [
        '10.0.0.0/8',
        '192.168.0.0/16'
      ],
    );
