apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud-staging
resources:
  - ../../base
  - avp-secret.yaml
configMapGenerator:
- name: db
  literals:
    - MYSQL_HOST=nextcloud-db-staging
- name: redis
  literals:
    - REDIS_HOST=nextcloud-redis-staging
- name: config-nginx
  files:
  - custom-nginx.conf=configmap-nginx.conf
transformers:
  - transformer-label.yaml
  - transformer-suffixprefix.yaml
images:
  - name: web
    newName: nginx
    newTag: "1.25.3-alpine"
  - name: app
    newName: nextcloud
    newTag: "28.0.2-fpm-alpine"
  - name: cron
    newName: nextcloud
    newTag: "28.0.2-fpm-alpine"
  - name: redis
    newName: redis
    newTag: "7.2.4-alpine"
  - name: db
    newName: mariadb
    newTag: "10.5"
patches:
### storage ###
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: nextcloud
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: nextcloud
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: nextcloud-db
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: nextcloud-db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
### reesources ###
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nextcloud
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nextcloud
      spec:
        template:
          spec:
            containers:
            - name: nextcloud
              resources:
                requests:
                  cpu: "3500m"
                  memory: "500Mi"
                limits:
                  cpu: "850m"
                  memory: "1000Mi"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nextcloud-db
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nextcloud-db
      spec:
        template:
          spec:
            containers:
            - name: nextcloud-db
              resources:
                requests:
                  cpu: "250m"
                  memory: "250Mi"
                limits:
                  cpu: "500m"
                  memory: "500Mi"
