apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app.kubernetes.io/name: nextcloud-minio
    app.kubernetes.io/component: minio
  ports:
  - name: tcp01
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: tcp02
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud-minio
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud-minio
        app.kubernetes.io/component: minio
    spec:
      containers:
      - name: minio
        image: minio
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        args:
        - server
        - /data
        - --console-address
        - :9090
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef: 
              name: db
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: MINIO_ROOT_PASSWORD
        ports:
        - containerPort: 9000
          name: tcp01
          protocol: TCP
        - containerPort: 9090
          name: tcp02
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
      initContainers:
      - name: init-volume
        image: busybox:1.28
        command: ["sh", "-c"]
        args:
        - mkdir -p /data/nextcloud
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio
